# sequence of build life cycle is correct as per standards
#below two line are taken for old repo 
#sudo: false
#dist: trusty

language: node_js
node_js:
  - "11"
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update      

install:
  - npm install


after_install:
  - echo "echoing in after_install steps"
  # - npm rebuild node-sass
  # - ./node_modules/protractor/bin/webdriver-manager update

before_script:
  - npm rebuild node-sass
  - echo "ignore sh -e /etc/init.d/xvfb start because not using trusty os image"
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sleep 3

script:
  - npm run test

after_success:
  - echo "scripts ( npm run test ) success , auto merge can be also triggerd"
  # - "BRANCHES_TO_MERGE_REGEX='^' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=a ./merge.sh"

env:
  global:
  - secure: abc
  - secure: xyz


after_failure:
    - echo "echoing in after_failure steps"
    - echo "trigger email to commit author for failure"

before_deploy:
- echo "pre steps for genrating artifacts for github gh-pages and relative public url in npm run build"
- PUBLIC_URL=https://nirajkashyap.github.io/react-microfrotend npm run build
- ls
- git status
- pwd
# - test $TRAVIS_TEST_RESULT = 0 \# check that build passed successfully
  # && cd $TRAVIS_BUILD_DIR \
  # && tar -zcvf amber-storm-$TRAVIS_BRANCH.tar.gz dist

# deploy:
#   provider: releases
#   api_key:
#     secure: securekeyhere
#   file: myrepo-$TRAVIS_BRANCH.tar.gz
#   skip_cleanup: true
#   on:
#     condition: $PRODBUILDCOMPLETE = true    
#     all_branches: true
#     tags: true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token_value  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir : build
  target_branch : gh-pages
  on:
    branch: master   



# after_deploy:
#   - ssh git@mysite.biz "./deploy.sh $TRAVIS_BRANCH"      

after_script:
- 'echo "echoing in after_script steps and will public coverage to coveralls"  '
- cat ./coverage/lcov.info | coveralls