

export const FETCH_GITHUB_ORG_START = 'FETCH_GITHUB_ORG_START';
export type FETCH_GITHUB_ORG_START = typeof FETCH_GITHUB_ORG_START;
export const FETCH_GITHUB_ORG_DETAILS = 'FETCH_GITHUB_ORG_DETAILS';
export type FETCH_GITHUB_ORG_DETAILS = typeof FETCH_GITHUB_ORG_DETAILS;
export const FETCH_GITHUB_ORG_DETAILS_FULFILLED = 'FETCH_GITHUB_ORG_DETAILS_FULFILLED';
export type FETCH_GITHUB_ORG_DETAILS_FULFILLED = typeof FETCH_GITHUB_ORG_DETAILS_FULFILLED;
export const FETCH_GITHUB_ORG_DETAILS_CANCEL = 'FETCH_GITHUB_ORG_DETAILS_CANCEL';
export type FETCH_GITHUB_ORG_DETAILS_CANCEL = typeof FETCH_GITHUB_ORG_DETAILS_CANCEL;
export const FETCH_GITHUB_ORG_DETAILS_FAILED = 'FETCH_GITHUB_ORG_DETAILS_FAILED';
export type FETCH_GITHUB_ORG_DETAILS_FAILED = typeof FETCH_GITHUB_ORG_DETAILS_FAILED;


export const FETCH_GITHUB_ORG_REPO_START = 'FETCH_GITHUB_ORG_REPO_START';
export type FETCH_GITHUB_ORG_REPO_START = typeof FETCH_GITHUB_ORG_REPO_START;
export const FETCH_GITHUB_ORG_REPO_DETAILS = 'FETCH_GITHUB_ORG_REPO_DETAILS';
export type FETCH_GITHUB_ORG_REPO_DETAILS = typeof FETCH_GITHUB_ORG_REPO_DETAILS;
export const FETCH_GITHUB_ORG_REPO_FULFILLED = 'FETCH_GITHUB_ORG_REPO_FULFILLED';
export type FETCH_GITHUB_ORG_REPO_FULFILLED = typeof FETCH_GITHUB_ORG_REPO_FULFILLED;
export const FETCH_GITHUB_ORG_REPO_CANCEL = 'FETCH_GITHUB_ORG_REPO_CANCEL';
export type FETCH_GITHUB_ORG_REPO_CANCEL = typeof FETCH_GITHUB_ORG_REPO_CANCEL;
export const FETCH_GITHUB_ORG_REPO_FAILED = 'FETCH_GITHUB_ORG_REPO_FAILED';
export type FETCH_GITHUB_ORG_REPO_FAILED = typeof FETCH_GITHUB_ORG_REPO_FAILED;


