export const LOGIN_START = 'LOGIN_START';
export type LOGIN_START = typeof LOGIN_START;

export const LOGIN_FULLFILLED = 'LOGIN_FULLFILLED';
export type LOGIN_FULLFILLED = typeof LOGIN_FULLFILLED;

export const LOGOUT = 'LOGOUT';
export type LOGOUT = typeof LOGOUT;




export const FETCH_GITHUB_USER_START = 'FETCH_GITHUB_USER_START';
export type FETCH_GITHUB_USER_START = typeof FETCH_GITHUB_USER_START;
export const FETCH_GITHUB_USER_DETAILS = 'FETCH_GITHUB_USER_DETAILS';
export type FETCH_GITHUB_USER_DETAILS = typeof FETCH_GITHUB_USER_DETAILS;
export const FETCH_GITHUB_USER_DETAILS_FULFILLED = 'FETCH_GITHUB_USER_DETAILS_FULFILLED';
export type FETCH_GITHUB_USER_DETAILS_FULFILLED = typeof FETCH_GITHUB_USER_DETAILS_FULFILLED;
export const FETCH_GITHUB_USER_DETAILS_CANCEL = 'FETCH_GITHUB_USER_DETAILS_CANCEL';
export type FETCH_GITHUB_USER_DETAILS_CANCEL = typeof FETCH_GITHUB_USER_DETAILS_CANCEL;
export const FETCH_GITHUB_USER_DETAILS_FAILED = 'FETCH_GITHUB_USER_DETAILS_FAILED';
export type FETCH_GITHUB_USER_DETAILS_FAILED = typeof FETCH_GITHUB_USER_DETAILS_FAILED;


export const FETCH_GITHUB_USER_REPO_START = 'FETCH_GITHUB_USER_REPO_START';
export type FETCH_GITHUB_USER_REPO_START = typeof FETCH_GITHUB_USER_REPO_START;
export const FETCH_GITHUB_USER_REPO_DETAILS = 'FETCH_GITHUB_USER_REPO_DETAILS';
export type FETCH_GITHUB_USER_REPO_DETAILS = typeof FETCH_GITHUB_USER_REPO_DETAILS;
export const FETCH_GITHUB_USER_REPO_FULFILLED = 'FETCH_GITHUB_USER_REPO_FULFILLED';
export type FETCH_GITHUB_USER_REPO_FULFILLED = typeof FETCH_GITHUB_USER_REPO_FULFILLED;
export const FETCH_GITHUB_USER_REPO_CANCEL = 'FETCH_GITHUB_USER_REPO_CANCEL';
export type FETCH_GITHUB_USER_REPO_CANCEL = typeof FETCH_GITHUB_USER_REPO_CANCEL;
export const FETCH_GITHUB_USER_REPO_FAILED = 'FETCH_GITHUB_USER_REPO_FAILED';
export type FETCH_GITHUB_USER_REPO_FAILED = typeof FETCH_GITHUB_USER_REPO_FAILED;


